#creates pairs of versions using zip_keys, lists must be the same length
python:
  - 3.8
  - 3.8
  - 3.9
  - 3.9
  - 3.9
  - 3.10 
  - 3.10
numpy:
  - 1.21
  - 1.22
  - 1.20
  - 1.21
  - 1.22
  - 1.21
  - 1.22
zip_keys:
  - python
  - numpy
