name: docs
channels:
  - conda-forge
  - ccpi
  - defaults
  - astra-toolbox/label/dev
dependencies:
  - dxchange
  - python-wget
  - scikit-image
  - packaging
  - tomophantom
  - numba
  - tigre
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - pydata-sphinx-theme
  - sphinx=3.5.*
  - recommonmark=0.6.*
  - sphinx-panels=0.5
  - sphinx-autobuild=0.7
  - sphinx-click=2.7
  - sphinx-copybutton=0.3
  - cil-astra
  - ccpi-regulariser
  - tomophantom