name: docs
channels:
  - conda-forge
  - intel
  - ccpi
  - defaults
  - astra-toolbox
dependencies:
  - dxchange
  - python-wget
  - scikit-image
  - packaging
  - numba
  - tigre=2.2
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - pydata-sphinx-theme<0.9
  - sphinx=3.5.*
  - recommonmark=0.6.*
  - sphinx-panels=0.5
  - sphinx-autobuild=0.7
  - sphinx-click=2.7
  - sphinx-copybutton=0.3
  - astra-toolbox>=1.9.9.dev5,<2.1
  - ccpi-regulariser=21.0.0
  - tomophantom=1.4.10
  - ipywidgets
  - tqdm
  - cil-data
